const $ = (id) => document.getElementById(id);
const esc = (x) => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18n = window.I18n;
const tr = (key, vars) => (I18n ? I18n.t(key, vars) : key);
const fixed2 = (value) => (I18n ? I18n.number(Number(value), {minimumFractionDigits:2, maximumFractionDigits:2}) : Number(value).toFixed(2));
function profileMeta(id) { if(id==='fast-code')return ['DeepSeek Flash',tr('profile.fast.generic'),'fast']; if(id==='senior-code')return ['Kimi K2.8',tr('profile.generic'),'senior']; if(id==='deep-research')return ['Kimi K3',tr('profile.deep'),'deep']; return null; }
const activeStates = ['starting','running','stopping','uncertain'];
const attentionStates = ['failed','needs_attention','timed_out','uncertain'];
const externalIcon = '<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M6 3H3v10h10v-3M9 3h4v4M7 9l6-6"/></svg>';
const folderIcon = '<svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 5h5l2 2h7v8H2zM2 5V3h5l2 2h7v2"/></svg>';
let data = {tasks:[],quota:{}}, selectedGroup = '', selectedFilter = 'all', selectedTask = null, loading = false;
function setHTML(el, value) { if (el.innerHTML !== value) el.innerHTML = value; }
function clock(seconds) { return seconds ? (I18n ? I18n.time(seconds,{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}) : new Date(seconds * 1000).toLocaleTimeString('en-GB',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'})) : '—'; }
function resetTime(value) { if (!value) return tr('reset.unknown'); const d = new Date(typeof value==='number' ? (value < 1e12 ? value*1000:value) : value); if(Number.isNaN(d.getTime()))return tr('reset.unknown'); const formatted = I18n ? I18n.date(d,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}) : d.toLocaleString(); return formatted+' '+tr('reset.suffix'); }
function duration(item) { if (!item.started_at) return tr('duration.waiting'); const s = Math.max(0, Math.round((item.finished_at || Date.now()/1000)-item.started_at)); if(s<60)return tr('duration.seconds',{n:s}); if(s<3600)return tr('duration.minutes',{m:Math.floor(s/60),s:s%60}); return tr('duration.hours',{h:Math.floor(s/3600),m:Math.floor(s%3600/60)}); }
function status(item) { const key='status.'+item.status; const text=I18n&&I18n.has(key)?tr(key):item.status; return `<span class="status ${esc(item.status)}"><i></i>${esc(text)}</span>`; }
function grouped() { const m=new Map(); for(const t of data.tasks){if(!m.has(t.group_id))m.set(t.group_id,{name:t.group_title,tasks:[]});m.get(t.group_id).tasks.push(t);} return m; }
function renderGroups() { let html=`<button class="nav-button ${!selectedGroup?'selected':''}" data-group="" aria-pressed="${!selectedGroup}">${folderIcon}<span class="nav-name">${tr('nav.allTasks')}</span><span class="nav-count">${data.tasks.length}</span></button>`;
 for(const [id,g] of grouped())html+=`<button class="nav-button ${id===selectedGroup?'selected':''}" data-group="${esc(id)}" aria-pressed="${id===selectedGroup}">${folderIcon}<span class="nav-name" title="${esc(g.name)}">${esc(g.name)}</span><span class="nav-count">${g.tasks.length}</span></button>`;setHTML($('groups'),html); }
function renderQuota(){const providers=new Set(Object.values(data.profiles||{}).map(p=>p.model.split('/')[0]));document.querySelector('.quota-block').hidden=!providers.has('deepseek');document.querySelector('.kimi-block').hidden=!providers.has('kimi-for-coding');document.querySelector('.quota-section').hidden=!providers.has('deepseek')&&!providers.has('kimi-for-coding');const ds=data.quota.deepseek||{}, k=data.quota['kimi-for-coding']||{};
 $('ds-balance').textContent=ds.balances?.length?ds.balances.map(b=>(b.currency==='CNY'?'¥':b.currency==='USD'?'$':b.currency+' ')+fixed2(b.remaining)).join(' / '):'—';
 $('ds-state').textContent=ds.state==='auth_error'?tr('quota.state.authError'):ds.available===false?tr('quota.state.unavailable'):ds.stale?tr('quota.state.stale'):ds.available===true?tr('quota.state.available'):tr('quota.state.unknown');
 $('ds-time').textContent=ds.sampled_at?tr('quota.sampledAt',{time:clock(ds.sampled_at)})+(ds.stale?tr('quota.lastSuccess'):''):tr('quota.noSample');
 const windows=k.windows||[];setHTML($('kimi-windows'),windows.length?windows.map(w=>{const p=w.remaining_percent;const name=w.name==='overall'?tr('quota.weekly'):w.duration_minutes?tr('quota.hoursWindow',{h:w.duration_minutes/60}):tr('quota.limitWindow');return `<div><div class="window-heading"><span>${esc(name)}</span><strong><small>${tr('quota.remaining')}</small>${p==null?'—':(I18n?I18n.number(Math.round(p)):Math.round(p))+'%'}</strong></div><progress class="quota-bar ${p<20?'low':''}" aria-label="${esc(tr('quota.remainingAria',{name}))}" max="100" ${p==null?'':`value="${Math.max(0,Math.min(100,p))}"`}></progress><div class="window-reset">${esc(resetTime(w.resets_at))}</div></div>`}).join(''):'<p class="muted">'+tr('quota.unknown')+'</p>');
 $('kimi-time').textContent=tr('quota.kimiShared')+(k.sampled_at?tr('quota.sampleSuffix',{time:clock(k.sampled_at)}):'')+(k.stale?tr('quota.staleSuffix'):'')+(k.state==='auth_error'?tr('quota.authErrorSuffix'):k.available===false?' · '+tr('quota.state.unavailable'):'');
}
function ordered(items){const ids=new Set(items.map(t=>t.id)),out=[],seen=new Set();function visit(t,depth){if(seen.has(t.id))return;seen.add(t.id);out.push([t,depth]);items.filter(x=>x.parent_task_id===t.id).forEach(x=>visit(x,depth+1));}items.filter(t=>!ids.has(t.parent_task_id)).forEach(t=>visit(t,0));items.forEach(t=>visit(t,0));return out;}
function renderTasks(){const q=$('search').value.trim().toLowerCase();let list=data.tasks.filter(t=>!selectedGroup||t.group_id===selectedGroup);const total=list.length;
 $('tasks-heading').textContent=selectedGroup?(grouped().get(selectedGroup)?.name||tr('common.primaryTask')):tr('nav.allTasks');
 $('counts').textContent=tr('counts.summary',{active:list.filter(t=>activeStates.includes(t.status)).length,queued:list.filter(t=>t.status==='queued').length});
 list=list.filter(t=>(selectedFilter==='all'||selectedFilter==='active'&&activeStates.includes(t.status)||selectedFilter==='attention'&&attentionStates.includes(t.status)||selectedFilter==='completed'&&t.status==='completed')&&(!q||[t.title,t.profile,data.profiles?.[t.profile]?.label,data.profiles?.[t.profile]?.model,t.group_title,t.id].join(' ').toLowerCase().includes(q)));
 const html=ordered(list).map(([t,depth])=>{const p=[...(profileMeta(t.profile)||(t.profile?[t.actual_models?.join(', ')||t.profile,tr('profile.generic'),'senior']:[tr('profile.awaiting'),tr('profile.auto'),'senior']))];if(data.profiles?.[t.profile]?.label)p[0]=data.profiles[t.profile].label;const title=t.session_url?`<a class="task-title" href="${esc(t.session_url)}" target="_blank" rel="noopener">${depth?'<span class="parent-indicator">└</span>':''}${esc(t.title)}${externalIcon}</a>`:`<span class="task-title no-session">${depth?'<span class="parent-indicator">└</span>':''}${esc(t.title)}</span>`;return `<tr><td>${title}<div class="task-meta">${esc(t.group_title)}${t.parent_task_id?tr('common.subtask'):''} · ${t.mode==='write'?tr('mode.write'):tr('mode.read')}${t.workspace==='isolated'?tr('mode.isolated'):''}</div></td><td><div class="worker-name"><i class="model-dot ${p[2]}"></i><div>${esc(p[0])}<small>${esc(p[1])}</small></div></div></td><td>${status(t)}</td><td class="duration">${duration(t)}</td><td><button class="detail-button" data-detail="${esc(t.id)}" aria-label="${esc(tr('task.viewDetails',{title:t.title}))}"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="m7 4 5 5-5 5"/></svg></button></td></tr>`}).join('');
 setHTML($('task-rows'),html||`<tr><td colspan="5" class="empty">${data.tasks.length?tr('tasks.emptyFiltered'):tr('tasks.emptyNone')}</td></tr>`);$('visible-count').textContent=tr('tasks.visibleCount',{visible:list.length,total});
}
async function request(path,options){const response=await fetch(path,options);if(!response.ok){let body={};try{body=await response.json();}catch{}throw new Error(body.error||(response.status===401?tr('error.connectionUpdated'):tr('error.unavailable')));}return response.json();}
async function refresh(){if(loading)return;loading=true;try{data=await request('/console-api/state');renderGroups();renderQuota();renderTasks();$('health').classList.toggle('offline',!data.pool_healthy);$('health').innerHTML=`<i></i>${data.pool_healthy?tr('health.online'):tr('health.offline')}`;$('updated').textContent=tr('updated.at',{time:clock(data.updated_at)});$('pool-limit').textContent=tr('pool.limit',{n:data.max_parallel_per_owner});$('error').hidden=true;}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('health').classList.add('offline');$('health').innerHTML='<i></i>'+tr('health.disconnected');}finally{loading=false;}}
function listHTML(items,empty){return items?.length?'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="muted">'+empty+'</p>';}
async function details(id){selectedTask=id;$('detail').hidden=false;$('detail-title').textContent=tr('detail.loading');$('detail-body').textContent='';try{const d=await request('/console-api/task/'+encodeURIComponent(id));if(selectedTask!==id)return;const t=d.task,r=d.report||{};$('detail-title').textContent=t.title;setHTML($('detail-body'),`<div class="detail-content"><div><h3>${tr('detail.objective')}</h3><p>${esc(d.objective)}</p><h3>${tr('detail.acceptance')}</h3>${listHTML(d.acceptance,tr('detail.noAcceptance'))}<h3>${tr('detail.statusOwnership')}</h3>${['running','uncertain'].includes(t.status)?`<button class="primary-button" data-steer-task="${esc(t.id)}">${tr('detail.steer')}</button>`:''}${['queued',...activeStates].includes(t.status)?`<button class="secondary-button" data-cancel-task="${esc(t.id)}">${tr('detail.stop')}</button>`:''}<p>${status(t)} · ${esc(t.group_title)}${t.parent_task_id?' / '+esc(t.parent_task_id):''}</p>${t.reason||t.queue_reason?'<p>'+esc(t.reason||t.queue_reason)+'</p>':''}${d.errors?.length?'<h3>'+tr('detail.errors')+'</h3>'+listHTML(d.errors.map(e=>[e.source,e.code,e.message,e.command?tr('detail.command')+e.command:'',e.exit_code!=null?tr('detail.exitCode')+e.exit_code:'',e.suggested_action?tr('detail.suggestedAction')+e.suggested_action:''].filter(Boolean).join(' · ')),''):''}${d.pending?.length?'<h3>'+tr('detail.pending')+'</h3>'+listHTML(d.pending.map(p=>JSON.stringify(p)),''):''}${t.guidance?.length?'<h3>'+tr('detail.guidance')+'</h3>'+listHTML(t.guidance.map(g=>g.status+' · '+g.text),''):''}<div class="detail-code">${esc(t.id)}<br>${esc(t.directory||t.source_dir)}</div>${d.session_url?`<a class="detail-link" href="${esc(d.session_url)}" target="_blank" rel="noopener">${tr('detail.openTask')}</a>`:'<p class="muted">'+tr('detail.noSession')+'</p>'}</div><div><h3>${tr('detail.workerSummary')}</h3><p>${esc(r.summary||t.summary||tr('detail.summaryPlaceholder'))}</p><h3>${tr('detail.evidence')}</h3>${listHTML(r.evidence,tr('detail.noEvidence'))}<h3>${tr('detail.tests')}</h3>${listHTML(r.tests,tr('detail.noTests'))}<h3>${tr('detail.unresolved')}</h3>${listHTML(r.unresolved,tr('detail.unresolvedDefault'))}</div></div>`);$('detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}catch(e){$('detail-title').textContent=tr('detail.unreadable');$('detail-body').textContent=e.message;}}
$('groups').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;selectedGroup=b.dataset.group;renderGroups();renderTasks();});
$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;selectedFilter=b.dataset.filter;for(const x of $('filters').querySelectorAll('button')){x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));}renderTasks();});
$('search').addEventListener('input',renderTasks);$('task-rows').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)details(b.dataset.detail);});
$('close-detail').addEventListener('click',()=>{selectedTask=null;$('detail').hidden=true;});
$('refresh-quota').addEventListener('click',async()=>{const b=$('refresh-quota');b.disabled=true;try{await request('/console-api/quota',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refresh();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}finally{b.disabled=false;}});
refresh();setInterval(()=>{if(!document.hidden)refresh();},4000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
document.addEventListener('i18n:change',()=>{renderGroups();renderQuota();renderTasks();$('health').innerHTML='<i></i>'+(data.pool_healthy?tr('health.online'):tr('health.offline'));if(data.updated_at)$('updated').textContent=tr('updated.at',{time:clock(data.updated_at)});if(data.max_parallel_per_owner!=null)$('pool-limit').textContent=tr('pool.limit',{n:data.max_parallel_per_owner});if(selectedTask)details(selectedTask);});
