const $ = (id) => document.getElementById(id);
const esc = (x) => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {queued:'排队中',starting:'准备中',running:'运行中',stopping:'停止中',uncertain:'状态待确认',completed:'已完成',failed:'失败',cancelled:'已取消',timed_out:'已超时',needs_attention:'需要处理'};
const profileNames = {'fast-code':['DeepSeek Flash','快速通用','fast'],'senior-code':['Kimi K2.8','通用任务','senior'],'deep-research':['Kimi K3','深度任务','deep']};
const activeStates = ['starting','running','stopping','uncertain'];
const attentionStates = ['failed','needs_attention','timed_out','uncertain'];
const externalIcon = '<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M6 3H3v10h10v-3M9 3h4v4M7 9l6-6"/></svg>';
const folderIcon = '<svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 5h5l2 2h7v8H2zM2 5V3h5l2 2h7v2"/></svg>';
let data = {tasks:[],quota:{}}, selectedGroup = '', selectedFilter = 'all', selectedTask = null, loading = false;
function setHTML(el, value) { if (el.innerHTML !== value) el.innerHTML = value; }
function clock(seconds) { return seconds ? new Date(seconds * 1000).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '—'; }
function resetTime(value) { if (!value) return '重置时间未知'; const d = new Date(typeof value==='number' ? (value < 1e12 ? value*1000:value) : value); return Number.isNaN(d.getTime())?'重置时间未知':d.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})+' 重置'; }
function duration(t) { if (!t.started_at) return '等待派发'; const s = Math.max(0, Math.round((t.finished_at || Date.now()/1000)-t.started_at)); if(s<60)return `${s} 秒`; if(s<3600)return `${Math.floor(s/60)} 分 ${s%60} 秒`; return `${Math.floor(s/3600)} 小时 ${Math.floor(s%3600/60)} 分`; }
function status(t) { return `<span class="status ${esc(t.status)}"><i></i>${esc(labels[t.status]||t.status)}</span>`; }
function grouped() { const m=new Map(); for(const t of data.tasks){if(!m.has(t.group_id))m.set(t.group_id,{name:t.group_title,tasks:[]});m.get(t.group_id).tasks.push(t);} return m; }
function renderGroups() { let html=`<button class="nav-button ${!selectedGroup?'selected':''}" data-group="" aria-pressed="${!selectedGroup}">${folderIcon}<span class="nav-name">全部任务</span><span class="nav-count">${data.tasks.length}</span></button>`;
 for(const [id,g] of grouped())html+=`<button class="nav-button ${id===selectedGroup?'selected':''}" data-group="${esc(id)}" aria-pressed="${id===selectedGroup}">${folderIcon}<span class="nav-name" title="${esc(g.name)}">${esc(g.name)}</span><span class="nav-count">${g.tasks.length}</span></button>`;setHTML($('groups'),html); }
function renderQuota(){const providers=new Set(Object.values(data.profiles||{}).map(p=>p.model.split('/')[0]));document.querySelector('.quota-block').hidden=!providers.has('deepseek');document.querySelector('.kimi-block').hidden=!providers.has('kimi-for-coding');document.querySelector('.quota-section').hidden=!providers.has('deepseek')&&!providers.has('kimi-for-coding');const ds=data.quota.deepseek||{}, k=data.quota['kimi-for-coding']||{};
 $('ds-balance').textContent=ds.balances?.length?ds.balances.map(b=>(b.currency==='CNY'?'¥':b.currency==='USD'?'$':b.currency+' ')+Number(b.remaining).toFixed(2)).join(' / '):'—';
 $('ds-state').textContent=ds.state==='auth_error'?'凭据失效':ds.stale?'数据待更新':ds.available===false?'不可用':ds.available===true?'可用':'状态未知';
 $('ds-time').textContent=ds.sampled_at?`采样 ${clock(ds.sampled_at)}${ds.stale?' · 最近成功数据':''}`:'尚无成功采样';
 const windows=k.windows||[];setHTML($('kimi-windows'),windows.length?windows.map(w=>{const p=w.remaining_percent;const name=w.name==='overall'?'周额度':w.duration_minutes?`${w.duration_minutes/60} 小时窗口`:'限制窗口';return `<div><div class="window-heading"><span>${esc(name)}</span><strong><small>剩余</small>${p==null?'—':Math.round(p)+'%'}</strong></div><progress class="quota-bar ${p<20?'low':''}" aria-label="${esc(name)}剩余额度" max="100" ${p==null?'':`value="${Math.max(0,Math.min(100,p))}"`}></progress><div class="window-reset">${esc(resetTime(w.resets_at))}</div></div>`}).join(''):'<p class="muted">额度未知，等待成功采样</p>');
 $('kimi-time').textContent=`K2.8 与 K3 共用额度池${k.sampled_at?' · 采样 '+clock(k.sampled_at):''}${k.stale?' · 数据待更新':''}${k.state==='auth_error'?' · 凭据失效':''}`;
}
function ordered(items){const ids=new Set(items.map(t=>t.id)),out=[],seen=new Set();function visit(t,depth){if(seen.has(t.id))return;seen.add(t.id);out.push([t,depth]);items.filter(x=>x.parent_task_id===t.id).forEach(x=>visit(x,depth+1));}items.filter(t=>!ids.has(t.parent_task_id)).forEach(t=>visit(t,0));items.forEach(t=>visit(t,0));return out;}
function renderTasks(){const q=$('search').value.trim().toLowerCase();let list=data.tasks.filter(t=>!selectedGroup||t.group_id===selectedGroup);const total=list.length;
 $('tasks-heading').textContent=selectedGroup?(grouped().get(selectedGroup)?.name||'主任务'):'全部任务';
 $('counts').textContent=`${list.filter(t=>activeStates.includes(t.status)).length} 执行中 · ${list.filter(t=>t.status==='queued').length} 排队中`;
 list=list.filter(t=>(selectedFilter==='all'||selectedFilter==='active'&&activeStates.includes(t.status)||selectedFilter==='attention'&&attentionStates.includes(t.status)||selectedFilter==='completed'&&t.status==='completed')&&(!q||[t.title,t.profile,data.profiles?.[t.profile]?.label,data.profiles?.[t.profile]?.model,t.group_title,t.id].join(' ').toLowerCase().includes(q)));
 const html=ordered(list).map(([t,depth])=>{const p=[...(profileNames[t.profile]||(t.profile?[t.actual_models?.join(', ')||t.profile,'通用任务','senior']:['等待调度','自动选择','senior']))];if(data.profiles?.[t.profile]?.label)p[0]=data.profiles[t.profile].label;const title=t.session_url?`<a class="task-title" href="${esc(t.session_url)}" target="_blank" rel="noopener">${depth?'<span class="parent-indicator">└</span>':''}${esc(t.title)}${externalIcon}</a>`:`<span class="task-title no-session">${depth?'<span class="parent-indicator">└</span>':''}${esc(t.title)}</span>`;return `<tr><td>${title}<div class="task-meta">${esc(t.group_title)}${t.parent_task_id?' · 子任务':''} · ${t.mode==='write'?'编写':'调查 / 分析'}${t.workspace==='isolated'?' · 独立工作树':''}</div></td><td><div class="worker-name"><i class="model-dot ${p[2]}"></i><div>${esc(p[0])}<small>${esc(p[1])}</small></div></div></td><td>${status(t)}</td><td class="duration">${duration(t)}</td><td><button class="detail-button" data-detail="${esc(t.id)}" aria-label="查看 ${esc(t.title)} 的详情"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="m7 4 5 5-5 5"/></svg></button></td></tr>`}).join('');
 setHTML($('task-rows'),html||`<tr><td colspan="5" class="empty">${data.tasks.length?'没有符合筛选条件的任务。':'还没有任务。Astra 派发后，任务会自动出现在这里。'}</td></tr>`);$('visible-count').textContent=`显示 ${list.length} / ${total} 项任务`;
}
async function request(path,options){const response=await fetch(path,options);if(!response.ok){let body={};try{body=await response.json();}catch{}throw new Error(body.error||(response.status===401?'连接已更新，请刷新页面重新连接。':'暂时无法读取本地服务，请稍后重试。'));}return response.json();}
async function refresh(){if(loading)return;loading=true;try{data=await request('/console-api/state');renderGroups();renderQuota();renderTasks();$('health').classList.toggle('offline',!data.pool_healthy);$('health').innerHTML=`<i></i>${data.pool_healthy?'本地服务在线':'本地服务待恢复'}`;$('updated').textContent='更新于 '+clock(data.updated_at);$('pool-limit').textContent=`并行上限 ${data.max_parallel} · 本地时间`;$('error').hidden=true;}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('health').classList.add('offline');$('health').innerHTML='<i></i>连接中断';}finally{loading=false;}}
function listHTML(items,empty){return items?.length?'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="muted">'+empty+'</p>';}
async function details(id){selectedTask=id;$('detail').hidden=false;$('detail-title').textContent='正在读取详情…';$('detail-body').textContent='';try{const d=await request('/console-api/task/'+encodeURIComponent(id));if(selectedTask!==id)return;const t=d.task,r=d.report||{};$('detail-title').textContent=t.title;setHTML($('detail-body'),`<div class="detail-content"><div><h3>任务目标</h3><p>${esc(d.objective)}</p><h3>验收条件</h3>${listHTML(d.acceptance,'未指定额外验收条件')}<h3>状态与归属</h3>${['running','uncertain'].includes(t.status)?`<button class="primary-button" data-steer-task="${esc(t.id)}">发送引导</button>`:''}${['queued',...activeStates].includes(t.status)?`<button class="secondary-button" data-cancel-task="${esc(t.id)}">停止任务</button>`:''}<p>${status(t)} · ${esc(t.group_title)}${t.parent_task_id?' / '+esc(t.parent_task_id):''}</p>${t.reason||t.queue_reason?'<p>'+esc(t.reason||t.queue_reason)+'</p>':''}${d.errors?.length?'<h3>错误回传</h3>'+listHTML(d.errors.map(e=>[e.source,e.code,e.message,e.command?'命令：'+e.command:'',e.exit_code!=null?'退出码：'+e.exit_code:'',e.suggested_action?'处理：'+e.suggested_action:''].filter(Boolean).join(' · ')),''):''}${d.pending?.length?'<h3>等待补充的信息</h3>'+listHTML(d.pending.map(p=>JSON.stringify(p)),''):''}${t.guidance?.length?'<h3>引导记录</h3>'+listHTML(t.guidance.map(g=>g.status+' · '+g.text),''):''}<div class="detail-code">${esc(t.id)}<br>${esc(t.directory||t.source_dir)}</div>${d.session_url?`<a class="detail-link" href="${esc(d.session_url)}" target="_blank" rel="noopener">在 OpenCode 中打开任务 ↗</a>`:'<p class="muted">任务尚未创建 OpenCode 会话。</p>'}</div><div><h3>Worker 摘要</h3><p>${esc(r.summary||t.summary||'结果将在任务完成后显示。')}</p><h3>证据</h3>${listHTML(r.evidence,'暂无回传证据')}<h3>测试与验证</h3>${listHTML(r.tests,'暂无测试记录')}<h3>待确认事项</h3>${listHTML(r.unresolved,'以主 Agent 最终审查为准')}</div></div>`);$('detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}catch(e){$('detail-title').textContent='暂时无法读取';$('detail-body').textContent=e.message;}}
$('groups').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;selectedGroup=b.dataset.group;renderGroups();renderTasks();});
$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;selectedFilter=b.dataset.filter;for(const x of $('filters').querySelectorAll('button')){x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));}renderTasks();});
$('search').addEventListener('input',renderTasks);$('task-rows').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)details(b.dataset.detail);});
$('close-detail').addEventListener('click',()=>{selectedTask=null;$('detail').hidden=true;});
$('refresh-quota').addEventListener('click',async()=>{const b=$('refresh-quota');b.disabled=true;try{await request('/console-api/quota',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refresh();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}finally{b.disabled=false;}});
refresh();setInterval(()=>{if(!document.hidden)refresh();},4000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
