let activeView='tasks', modelSettings=null, modelCatalog=[], sessionData=[], dialogSubmit=null, routingPolicyDraft={}, routingDynamicsDraft={};
const fixed1 = (value) => (I18n ? I18n.number(Number(value), {minimumFractionDigits:1, maximumFractionDigits:1}) : Number(value).toFixed(1));
function applyViewLabels(){$('page-title').textContent=tr('nav.'+activeView);$('page-description').textContent=tr('page.'+activeView+'.desc');}
const field=(name,label,value='',extra='')=>`<label>${esc(label)}<input name="${esc(name)}" value="${esc(value)}" ${extra}></label>`;
function notice(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
async function mutate(path,body){return request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
function openAction(title,html,submit){$('action-title').textContent=title;$('action-fields').innerHTML=html;$('action-error').textContent='';dialogSubmit=submit;$('action-dialog').showModal();}
function closeAction(){$('action-dialog').close();dialogSubmit=null;}
$('close-action').onclick=closeAction;$('cancel-action').onclick=closeAction;
$('action-form').onsubmit=async e=>{e.preventDefault();const button=$('confirm-action');button.disabled=true;$('action-error').textContent='';try{await dialogSubmit(Object.fromEntries(new FormData(e.target)));closeAction();}catch(error){$('action-error').textContent=error.message;}finally{button.disabled=false;}};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=async()=>{activeView=b.dataset.view;for(const x of document.querySelectorAll('[data-view]'))x.classList.toggle('selected',x===b);for(const x of document.querySelectorAll('.view-panel'))x.hidden=x.id!=='view-'+activeView;applyViewLabels();try{if(activeView==='sessions')await loadSessions();if(activeView==='models')await loadSettings();}catch(e){notice(e);}};
function sessionLink(s){return '/'+btoa(unescape(encodeURIComponent(s.directory))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')+'/session/'+encodeURIComponent(s.id);}
async function loadSessions(){await loadWorkspaces();const result=await request('/console-api/sessions');sessionData=result.sessions||[];const selected=$('session-project').value;$('session-project').innerHTML='<option value="">'+esc(tr('sessions.allProjects'))+'</option>'+(result.projects||[]).map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');$('session-project').value=selected;renderSessions();if(result.truncated)$('session-count').textContent+=' · '+tr('sessions.truncated');}
function renderSessions(){const q=$('session-search').value.toLowerCase(),project=$('session-project').value,archived=$('session-archived').checked;const list=sessionData.filter(s=>Boolean(s.time?.archived)===archived&&(!project||s.directory===project)&&(!q||[s.title,s.id].join(' ').toLowerCase().includes(q)));$('session-count').textContent=tr('sessions.count',{n:list.length});$('session-list').innerHTML=list.map(s=>{const busy=s.status==='busy'||s.status==='retry'||s.status?.type==='busy'||s.status?.type==='retry';return `<article class="session-card"><div class="session-main"><a class="session-title" href="${esc(sessionLink(s))}" target="_blank" rel="noopener">${esc(s.title||tr('sessions.untitled'))} ↗</a><div class="task-meta">${esc(s.directory)}</div><div class="task-meta">${s.task_id?tr('sessions.delegated')+' · '+esc(s.task_id):tr('nav.sessions')}${s.parentID?tr('sessions.branched'):''} · ${s.time?.updated?(I18n?I18n.dateTime(s.time.updated):new Date(s.time.updated).toLocaleString()):''}</div></div><div class="session-actions"><span class="status ${busy?'running':'completed'}">${busy?tr('status.running'):tr('status.idle')}</span><button data-session="${esc(s.id)}" data-action="rename" class="text-button">${tr('action.rename')}</button><button data-session="${esc(s.id)}" data-action="bind" class="text-button" ${busy?'disabled':''}>${tr('action.workspace')}</button><button data-session="${esc(s.id)}" data-action="fork" class="text-button" ${busy?'disabled':''}>${tr('action.fork')}</button><button data-session="${esc(s.id)}" data-action="${archived?'restore':'archive'}" class="text-button" ${busy?'disabled':''}>${archived?tr('action.restore'):tr('action.archive')}</button><button data-session="${esc(s.id)}" data-action="delete" class="text-button danger-text" ${busy?'disabled':''}>${tr('action.delete')}</button></div></article>`}).join('')||'<div class="empty">'+tr('sessions.empty')+'</div>';}
$('session-search').oninput=renderSessions;$('session-project').onchange=renderSessions;$('session-archived').onchange=renderSessions;$('refresh-sessions').onclick=()=>loadSessions().catch(notice);
$('session-list').onclick=e=>{const b=e.target.closest('[data-session]');if(!b)return;const s=sessionData.find(x=>x.id===b.dataset.session),action=b.dataset.action;const title=tr({rename:'dialog.renameSession',fork:'dialog.forkSession',archive:'dialog.archiveSession',restore:'dialog.restoreSession',delete:'dialog.deleteSession',bind:'dialog.bindWorkspace'}[action]);openAction(title,action==='bind'?field('directory',tr('field.directory'),s.directory,'required list="workspace-options"')+'<p class="muted">'+esc(tr('dialog.bindHint'))+'</p>':action==='delete'?`<p>${esc(tr('dialog.deleteWarning'))}</p><p><strong>${esc(s.title)}</strong></p>${field('confirm_title',tr('field.confirmTitle'),'','required autocomplete="off"')}`:action==='rename'?field('title',tr('field.sessionTitle'),s.title,'required maxlength="200"'):`<p>${esc(s.title)}</p><p class="muted">${esc(action==='fork'?tr('dialog.forkHint'):action==='archive'?tr('dialog.archiveHint'):tr('dialog.restoreHint'))}</p>`,async values=>{await mutate('/console-api/session/'+encodeURIComponent(s.id),{action,...values,...(action==='delete'?{confirm_session_id:s.id}:{})});await loadSessions();await refresh();});};
$('new-session').onclick=()=>openAction(tr('dialog.newSession'),field('directory',tr('field.directory'),'','required list="workspace-options" placeholder="/path/to/project"')+field('title',tr('field.sessionTitle'),'','required maxlength="200"'),async v=>{await mutate('/console-api/sessions',v);await loadSessions();});
function profileRows(){return [...$('profile-list').querySelectorAll('.profile-card')];}
function addProfile(id='',p={}){const card=document.createElement('div');card.className='profile-card';card.innerHTML=`<div class="profile-card-top"><strong>${esc(p.label||id||tr('profile.new'))}</strong><button type="button" class="text-button remove-profile">${tr('action.remove')}</button></div><div class="form-grid">${field('id',tr('field.profileId'),id,'required pattern="[a-z][a-z0-9-]*"')}${field('label',tr('field.displayName'),p.label||id,'maxlength="100"')}${field('model',tr('field.providerModel'),p.model||'','required list="model-options" placeholder="provider/model"')}${field('variant',tr('field.variant'),p.variant||'','placeholder="'+esc(tr('field.variantPlaceholder'))+'"')}</div><label class="check-label"><input name="enabled" type="checkbox" ${p.enabled===false?'':'checked'}>${tr('field.enabled')}</label>`;const update=()=>{renderRouting();renderRoutingPolicy();};card.querySelector('.remove-profile').onclick=()=>{card.remove();update();};card.querySelector('[name=id]').onchange=update;card.querySelector('[name=enabled]').onchange=update;$('profile-list').append(card);}
function readProfiles(){const result={};for(const card of profileRows()){const get=n=>card.querySelector(`[name=${n}]`).value.trim();const id=get('id');if(!/^[a-z][a-z0-9-]*$/.test(id))throw Error(tr('error.profileId'));if(result[id])throw Error(tr('error.profileDuplicate'));result[id]={model:get('model'),label:get('label')||id,enabled:card.querySelector('[name=enabled]').checked};if(get('variant'))result[id].variant=get('variant');}return result;}
function renderRouting(initial){let profiles;try{profiles=readProfiles();}catch{return;}for(const key of ['fast','background','deep']){const select=$('route-'+key),value=initial?.[key]||select.value;select.innerHTML=Object.entries(profiles).filter(([,p])=>p.enabled).map(([id,p])=>`<option value="${esc(id)}">${esc(p.label)} · ${esc(id)}</option>`).join('');if([...select.options].some(o=>o.value===value))select.value=value;}}
function routingPolicySummary(policy, profiles, dynamics={}){return ['fast','background','deep'].filter(k=>policy?.[k]?.length).map(k=>`<p><strong>${esc(tr('routing.'+k))}</strong> · ${policy[k].map((stage,i)=>stage.map(member=>esc(profiles[member.profile]?.label||member.profile)+(stage.length>1?' × '+esc(member.weight):'')).join(' + ')+(dynamics?.[k]?.[String(i)]?' · '+esc(tr('routing.adaptive')):'')).join(' → ')}</p>`).join('');}
function cloneRouting(value){return JSON.parse(JSON.stringify(value||{}));}
function enabledProfileIds(){try{return Object.entries(readProfiles()).filter(([,p])=>p.enabled).map(([id])=>id);}catch{return [];}}
function defaultLadder(stage){const a=Number(stage?.[0]?.weight)||1,b=Number(stage?.[1]?.weight)||1;return [[Math.min(100,a+1),b],[a,b],[a,Math.min(100,b+1)]];}
function ladderText(record,stage){return (record?.ladder||defaultLadder(stage)).map(pair=>pair.join(':')).join(', ');}
function parseLadder(value){const ratios=String(value).split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const m=x.match(/^(\d+)\s*:\s*(\d+)$/);if(!m)throw Error(tr('routing.invalidLadder'));return [Number(m[1]),Number(m[2])];});if(ratios.length<2)throw Error(tr('routing.invalidLadder'));return ratios;}
function readRoutingEditor(){if(!$('routing-policy-enabled').checked)return [{},{}];const policy={},dynamics={};for(const tier of ['fast','background','deep']){const tierNode=$('routing-policy-editor').querySelector(`[data-route-tier="${tier}"]`);const stages=[];for(const stageNode of tierNode?.querySelectorAll('.route-stage')||[]){const members=[...stageNode.querySelectorAll('.route-member')].map(row=>({profile:row.querySelector('[data-role=profile]').value,weight:Number(row.querySelector('[data-role=weight]').value)}));if(members.length)stages.push(members);const adaptive=stageNode.querySelector('[data-role=adaptive]');if(adaptive?.checked){const index=String(stages.length-1);(dynamics[tier]??={})[index]={ladder:parseLadder(stageNode.querySelector('[data-role=ladder]').value)};}}if(stages.length)policy[tier]=stages;}return [policy,dynamics];}
function captureRoutingEditor(){try{[routingPolicyDraft,routingDynamicsDraft]=readRoutingEditor();return true;}catch(e){$('settings-message').textContent=e.message;return false;}}
function policyTemplate(kind){const ids=enabledProfileIds(),policy={};for(const tier of ['fast','background','deep']){const primary=$('route-'+tier).value||ids[0],backup=ids.find(id=>id!==primary);if(!primary)continue;if(kind==='backup')policy[tier]=backup?[[{profile:primary,weight:1}],[{profile:backup,weight:1}]]:[[{profile:primary,weight:1}]];else if(kind==='pool')policy[tier]=[[{profile:primary,weight:1},...(backup?[{profile:backup,weight:1}]:[])]];}routingPolicyDraft=policy;routingDynamicsDraft={};$('routing-policy-enabled').checked=kind!=='single';renderRoutingPolicy();}
function renderRoutingPolicy(){const enabled=$('routing-policy-enabled').checked,profiles=(()=>{try{return readProfiles();}catch{return modelSettings?.profiles||{};}})(),ids=Object.entries(profiles).filter(([,p])=>p.enabled).map(([id])=>id);for(const key of ['fast','background','deep'])$('route-'+key).disabled=enabled&&Boolean(routingPolicyDraft[key]?.length);$('routing-policy-summary').innerHTML=enabled?routingPolicySummary(routingPolicyDraft,profiles,routingDynamicsDraft):'';$('routing-policy-editor').hidden=!enabled;if(!enabled){$('routing-policy-editor').innerHTML='';return;}$('routing-policy-editor').innerHTML=['fast','background','deep'].map(tier=>{const stages=routingPolicyDraft[tier]||[];return `<section class="route-tier" data-route-tier="${tier}"><div class="route-tier-head"><strong>${esc(tr('routing.'+tier))}</strong><button type="button" class="text-button" data-route-action="add-stage" data-tier="${tier}">${esc(tr('routing.addFallback'))}</button></div>${stages.map((stage,si)=>`<div class="route-stage" data-stage="${si}"><div class="route-stage-head"><span>${esc(tr('routing.stage',{n:si+1}))}</span><div><button type="button" class="text-button" data-route-action="add-member" data-tier="${tier}" data-stage="${si}">${esc(tr('routing.addModel'))}</button><button type="button" class="text-button danger-text" data-route-action="remove-stage" data-tier="${tier}" data-stage="${si}">${esc(tr('action.remove'))}</button></div></div>${stage.map((member,mi)=>`<div class="route-member"><select data-role="profile" aria-label="${esc(tr('field.profile'))}">${ids.map(id=>`<option value="${esc(id)}" ${id===member.profile?'selected':''}>${esc(profiles[id]?.label||id)} · ${esc(id)}</option>`).join('')}</select><label><span>${esc(tr('routing.weight'))}</span><input data-role="weight" type="number" min="1" max="100" value="${esc(member.weight)}"></label><button type="button" class="text-button danger-text" data-route-action="remove-member" data-tier="${tier}" data-stage="${si}" data-member="${mi}">${esc(tr('action.remove'))}</button></div>`).join('')}${stage.length===2?`<div class="route-adaptive"><label class="check-label"><input data-role="adaptive" type="checkbox" ${routingDynamicsDraft?.[tier]?.[String(si)]?'checked':''}><span>${esc(tr('routing.adaptiveLabel'))}</span></label><label><span>${esc(tr('routing.ladder'))}</span><input data-role="ladder" value="${esc(ladderText(routingDynamicsDraft?.[tier]?.[String(si)],stage))}" ${routingDynamicsDraft?.[tier]?.[String(si)]?'':'disabled'}></label><p class="muted">${esc(tr('routing.adaptiveHint'))}</p></div>`:''}</div>`).join('')}<button type="button" class="secondary-button route-empty-action" data-route-action="add-stage" data-tier="${tier}">${esc(stages.length?tr('routing.addFallback'):tr('routing.addFirstStage'))}</button></section>`;}).join('');}
$('routing-policy-enabled').onchange=()=>{if($('routing-policy-enabled').checked&&!Object.keys(routingPolicyDraft).length)policyTemplate('backup');else renderRoutingPolicy();};
$('routing-template-single').onclick=()=>policyTemplate('single');$('routing-template-backup').onclick=()=>policyTemplate('backup');$('routing-template-pool').onclick=()=>policyTemplate('pool');
$('routing-policy-editor').onchange=e=>{if(e.target.matches('[data-role=adaptive]'))e.target.closest('.route-stage').querySelector('[data-role=ladder]').disabled=!e.target.checked;captureRoutingEditor();routingPolicyDraft=cloneRouting(routingPolicyDraft);routingDynamicsDraft=cloneRouting(routingDynamicsDraft);renderRoutingPolicy();};
$('routing-policy-editor').onclick=e=>{const b=e.target.closest('[data-route-action]');if(!b)return;if(!captureRoutingEditor())return;const tier=b.dataset.tier,si=Number(b.dataset.stage),action=b.dataset.routeAction,ids=enabledProfileIds();if(action==='add-stage'){const used=new Set((routingPolicyDraft[tier]||[]).flat().map(x=>x.profile)),profile=ids.find(id=>!used.has(id));if(profile)(routingPolicyDraft[tier]??=[]).push([{profile,weight:1}]);}else if(action==='remove-stage'){routingPolicyDraft[tier].splice(si,1);routingDynamicsDraft[tier]={};}else if(action==='add-member'){const used=new Set(routingPolicyDraft[tier].flat().map(x=>x.profile)),profile=ids.find(id=>!used.has(id));if(profile)routingPolicyDraft[tier][si].push({profile,weight:1});}else if(action==='remove-member'){routingPolicyDraft[tier][si].splice(Number(b.dataset.member),1);if(!routingPolicyDraft[tier][si].length)routingPolicyDraft[tier].splice(si,1);routingDynamicsDraft[tier]={};}renderRoutingPolicy();};
async function loadSettings(){const [settings,catalog]=await Promise.all([request('/console-api/settings'),request('/console-api/models')]);modelSettings=settings;routingPolicyDraft=cloneRouting(settings.routing_policy);routingDynamicsDraft=cloneRouting(settings.routing_dynamics);const ec=settings.economics||{};$('economics-afp-unit').value=ec.afp_cny_per_unit??0.002;$('economics-kimi-price').value=ec.kimi_plan_cny??699;$('economics-auto').value=ec.ark_auto_afp_per_m??50;$('economics-evolving').value=ec.ark_evolving_afp_per_m??250;$('economics-k3').value=ec.ark_k3_afp_per_m??1000;$('routing-policy-enabled').checked=Boolean(Object.keys(routingPolicyDraft).length);const mr=settings.kimi_monthly_reset||{};$('kimi-monthly-enabled').checked=mr.enabled===true;$('kimi-monthly-day').value=mr.day??1;$('kimi-monthly-time').value=mr.time||'12:00';$('kimi-monthly-zone').value=mr.timezone||'Asia/Shanghai';$('auto-approve').checked=settings.auto_approve!==false;$('auto-reroute-quota').checked=settings.auto_reroute_on_quota_exhaustion!==false;const cp=settings.cleanup||{};$('cleanup-enabled').checked=!!cp.enabled;$('cleanup-min').value=cp.min_free_gb??5;$('cleanup-target').value=cp.target_free_gb??10;$('cleanup-age').value=cp.min_age_days??30;$('cleanup-keep').value=cp.keep_recent??20;modelCatalog=Array.isArray(catalog)?catalog:(catalog.providers||[]);$('profile-list').innerHTML='';for(const [id,p] of Object.entries(settings.profiles||{}))addProfile(id,p);$('max-parallel-per-owner').value=settings.max_parallel_per_owner??4;$('kimi-reserve').value=settings.kimi_reserve_percent;$('kimi-low-weekly-threshold').value=settings.kimi_low_weekly_threshold_percent??5;$('kimi-low-weekly-k3-limit').value=settings.kimi_low_weekly_k3_limit??1;renderRouting(settings.routing||{fast:'fallback',background:'senior-code',deep:'deep-research'});renderRoutingPolicy();$('model-options').innerHTML=modelCatalog.flatMap(p=>(Array.isArray(p.models)?p.models:Object.values(p.models||{})).map(m=>`<option value="${esc(p.id+'/'+m.id)}">${esc(m.name||m.id)}</option>`)).join('');$('provider-list').innerHTML=modelCatalog.map(p=>`<div class="provider-row"><strong>${esc(p.name||p.id)}</strong><span class="muted">${p.connected?tr('provider.connected'):tr('provider.disconnected')} · ${tr('provider.models',{n:Array.isArray(p.models)?p.models.length:Object.keys(p.models||{}).length})}</span></div>`).join('')||'<p class="muted">'+tr('provider.none')+'</p>';}
$('add-profile').onclick=()=>addProfile();$('reload-settings').onclick=()=>loadSettings().catch(notice);
$('save-settings').onclick=async()=>{const b=$('save-settings');b.disabled=true;$('settings-message').textContent=tr('settings.applying');try{const [routingPolicy,routingDynamics]=readRoutingEditor();const body={revision:modelSettings?.revision||0,auto_approve:$('auto-approve').checked,auto_reroute_on_quota_exhaustion:$('auto-reroute-quota').checked,economics:{afp_cny_per_unit:Number($('economics-afp-unit').value),kimi_plan_cny:Number($('economics-kimi-price').value),ark_auto_afp_per_m:Number($('economics-auto').value),ark_evolving_afp_per_m:Number($('economics-evolving').value),ark_k3_afp_per_m:Number($('economics-k3').value)},kimi_monthly_reset:{enabled:$('kimi-monthly-enabled').checked,day:Number($('kimi-monthly-day').value),time:$('kimi-monthly-time').value,timezone:$('kimi-monthly-zone').value.trim()},cleanup:{enabled:$('cleanup-enabled').checked,min_free_gb:Number($('cleanup-min').value),target_free_gb:Number($('cleanup-target').value),min_age_days:Number($('cleanup-age').value),keep_recent:Number($('cleanup-keep').value),interval_seconds:3600},profiles:readProfiles(),max_parallel_per_owner:Number($('max-parallel-per-owner').value),kimi_reserve_percent:Number($('kimi-reserve').value),kimi_low_weekly_threshold_percent:Number($('kimi-low-weekly-threshold').value),kimi_low_weekly_k3_limit:Number($('kimi-low-weekly-k3-limit').value),routing:Object.fromEntries(['fast','background','deep'].map(k=>[k,$('route-'+k).value])),routing_policy:routingPolicy,routing_dynamics:routingDynamics};const saved=await mutate('/console-api/settings',body);modelSettings=saved;$('settings-message').textContent=tr('settings.saved');await loadSettings();await refresh();}catch(e){$('settings-message').textContent=e.message;}finally{b.disabled=false;}};
$('new-task').onclick=()=>{openAction(tr('dialog.newTask'),field('title',tr('field.taskTitle'),'','required maxlength="200"')+field('directory',tr('field.directory'),'','required list="workspace-options" placeholder="/path/to/project"')+'<label>'+esc(tr('field.objective'))+'<textarea name="objective" required rows="4"></textarea></label>'+field('group_title',tr('field.groupTitle'),tr('field.manualTask'))+`<div class="form-grid"><label>${esc(tr('field.tier'))}<select name="tier"><option value="fast">${esc(tr('routing.fast'))}</option><option value="normal" selected>${esc(tr('routing.background'))}</option><option value="deep">${esc(tr('routing.deep'))}</option></select></label><label>${esc(tr('field.mode'))}<select name="mode"><option value="read">${esc(tr('field.readOnly'))}</option><option value="write">${esc(tr('field.write'))}</option></select></label><label>${esc(tr('field.workspace'))}<select name="workspace"><option value="auto">${esc(tr('field.auto'))}</option><option value="isolated">${esc(tr('field.isolated'))}</option></select></label></div><label>${esc(tr('field.acceptance'))}<textarea name="acceptance" rows="2"></textarea></label><label>${esc(tr('field.scopes'))}<textarea name="scopes" rows="2" placeholder="src/module.py"></textarea></label><label>${esc(tr('field.targets'))}<textarea name="targets" rows="2" placeholder="ssh:staging-api / service:api"></textarea></label><p class="muted">${esc(tr('field.targetHint'))}</p><label>${esc(tr('field.resources'))}<textarea name="resources" rows="2" placeholder="ssh:staging-api:api"></textarea></label><label>${esc(tr('field.commands'))}<textarea name="commands" rows="2" placeholder="python3 -m unittest -v"></textarea></label><p class="muted">${esc(tr('field.commandHint'))}</p>`,async v=>{const lines=s=>s.split('\n').map(x=>x.trim()).filter(Boolean);await mutate('/console-api/tasks',{...v,profile:'auto',scopes:lines(v.scopes),targets:lines(v.targets),resources:lines(v.resources),commands:lines(v.commands),acceptance:lines(v.acceptance),group_id:'manual:'+v.directory});await refresh();});};
document.addEventListener('click',e=>{const b=e.target.closest('[data-cancel-task]');if(!b)return;openAction(tr('dialog.stopTask'),'<p>'+esc(tr('dialog.stopHint'))+'</p>',async()=>{await mutate('/console-api/task/'+b.dataset.cancelTask+'/cancel',{});await refresh();});});
setInterval(()=>{if(activeView==='sessions'&&!document.hidden&&!$('action-dialog').open)loadSessions().catch(notice);},10000);

async function loadWorkspaces(){const items=await request('/console-api/workspaces');$('workspace-options').innerHTML=items.map(w=>`<option value="${esc(w.directory)}">${esc(w.name)}</option>`).join('');}
$('add-workspace').onclick=()=>openAction(tr('dialog.addWorkspace'),field('name',tr('field.workspaceName'),'','required maxlength="100"')+field('directory',tr('field.directory'),'','required'),async v=>{await mutate('/console-api/workspaces',v);await loadWorkspaces();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-steer-task]');if(!b)return;const requestId=crypto.randomUUID();openAction(tr('dialog.steer'),'<label>'+esc(tr('field.steerText'))+'<textarea name="text" required rows="5" maxlength="24000"></textarea></label><p class="muted">'+esc(tr('dialog.steerHint'))+'</p>',async v=>{const result=await mutate('/console-api/task/'+b.dataset.steerTask+'/steer',{text:v.text,request_id:requestId});if(result.status!=='accepted')throw Error(tr('error.steerStatus',{status:result.status}));await refresh();});});

$('cleanup-preview').onclick=async()=>{try{const p=await request('/console-api/cleanup');$('cleanup-message').textContent=tr('cleanup.previewResult',{free:fixed1(p.free_bytes/2**30),count:p.candidate_count,size:fixed1(p.candidate_bytes/2**20)}); }catch(e){$('cleanup-message').textContent=e.message;}};
$('cleanup-run').onclick=()=>openAction(tr('dialog.cleanup'),'<p>'+esc(tr('dialog.cleanupHint'))+'</p>',async()=>{const r=await mutate('/console-api/cleanup',{apply:true});$('cleanup-message').textContent=r.skipped?tr('cleanup.skipped',{reason:r.skipped}):tr('cleanup.done',{removed:r.removed.length,errors:r.errors.length});});
document.addEventListener('i18n:change',()=>{applyViewLabels();if(activeView==='sessions')loadSessions().catch(notice);else if(activeView==='models')loadSettings().catch(notice);});
