let activeView='tasks', modelSettings=null, modelCatalog=[], sessionData=[], dialogSubmit=null;
const fixed1 = (value) => (I18n ? I18n.number(Number(value), {minimumFractionDigits:1, maximumFractionDigits:1}) : Number(value).toFixed(1));
function applyViewLabels(){$('page-title').textContent=tr('nav.'+activeView);$('page-description').textContent=tr('page.'+activeView+'.desc');}
const field=(name,label,value='',extra='')=>`<label>${esc(label)}<input name="${esc(name)}" value="${esc(value)}" ${extra}></label>`;
function notice(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
async function mutate(path,body){return request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
function openAction(title,html,submit){$('action-title').textContent=title;$('action-fields').innerHTML=html;$('action-error').textContent='';dialogSubmit=submit;$('action-dialog').showModal();}
function closeAction(){$('action-dialog').close();dialogSubmit=null;}
$('close-action').onclick=closeAction;$('cancel-action').onclick=closeAction;
$('action-form').onsubmit=async e=>{e.preventDefault();const button=$('confirm-action');button.disabled=true;$('action-error').textContent='';try{await dialogSubmit(Object.fromEntries(new FormData(e.target)));closeAction();}catch(error){$('action-error').textContent=error.message;}finally{button.disabled=false;}};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=async()=>{activeView=b.dataset.view;for(const x of document.querySelectorAll('[data-view]'))x.classList.toggle('selected',x===b);for(const x of document.querySelectorAll('.view-panel'))x.hidden=x.id!=='view-'+activeView;applyViewLabels();try{if(activeView==='sessions')await loadSessions();if(activeView==='models')await loadSettings();}catch(e){notice(e);}};
function sessionLink(s){return '/'+btoa(unescape(encodeURIComponent(s.directory))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')+'/session/'+encodeURIComponent(s.id);}
async function loadSessions(){await loadWorkspaces();const result=await request('/console-api/sessions');sessionData=result.sessions||[];const selected=$('session-project').value;$('session-project').innerHTML='<option value="">'+esc(tr('sessions.allProjects'))+'</option>'+(result.projects||[]).map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');$('session-project').value=selected;renderSessions();if(result.truncated)$('session-count').textContent+=' · '+tr('sessions.truncated');}
function renderSessions(){const q=$('session-search').value.toLowerCase(),project=$('session-project').value,archived=$('session-archived').checked;const list=sessionData.filter(s=>Boolean(s.time?.archived)===archived&&(!project||s.directory===project)&&(!q||[s.title,s.id].join(' ').toLowerCase().includes(q)));$('session-count').textContent=tr('sessions.count',{n:list.length});$('session-list').innerHTML=list.map(s=>{const busy=s.status==='busy'||s.status==='retry'||s.status?.type==='busy'||s.status?.type==='retry';return `<article class="session-card"><div class="session-main"><a class="session-title" href="${esc(sessionLink(s))}" target="_blank" rel="noopener">${esc(s.title||tr('sessions.untitled'))} ↗</a><div class="task-meta">${esc(s.directory)}</div><div class="task-meta">${s.task_id?tr('sessions.delegated')+' · '+esc(s.task_id):tr('nav.sessions')}${s.parentID?tr('sessions.branched'):''} · ${s.time?.updated?(I18n?I18n.dateTime(s.time.updated):new Date(s.time.updated).toLocaleString()):''}</div></div><div class="session-actions"><span class="status ${busy?'running':'completed'}">${busy?tr('status.running'):tr('status.idle')}</span><button data-session="${esc(s.id)}" data-action="rename" class="text-button">${tr('action.rename')}</button><button data-session="${esc(s.id)}" data-action="bind" class="text-button" ${busy?'disabled':''}>${tr('action.workspace')}</button><button data-session="${esc(s.id)}" data-action="fork" class="text-button" ${busy?'disabled':''}>${tr('action.fork')}</button><button data-session="${esc(s.id)}" data-action="${archived?'restore':'archive'}" class="text-button" ${busy?'disabled':''}>${archived?tr('action.restore'):tr('action.archive')}</button><button data-session="${esc(s.id)}" data-action="delete" class="text-button danger-text" ${busy?'disabled':''}>${tr('action.delete')}</button></div></article>`}).join('')||'<div class="empty">'+tr('sessions.empty')+'</div>';}
$('session-search').oninput=renderSessions;$('session-project').onchange=renderSessions;$('session-archived').onchange=renderSessions;$('refresh-sessions').onclick=()=>loadSessions().catch(notice);
$('session-list').onclick=e=>{const b=e.target.closest('[data-session]');if(!b)return;const s=sessionData.find(x=>x.id===b.dataset.session),action=b.dataset.action;const title=tr({rename:'dialog.renameSession',fork:'dialog.forkSession',archive:'dialog.archiveSession',restore:'dialog.restoreSession',delete:'dialog.deleteSession',bind:'dialog.bindWorkspace'}[action]);openAction(title,action==='bind'?field('directory',tr('field.directory'),s.directory,'required list="workspace-options"')+'<p class="muted">'+esc(tr('dialog.bindHint'))+'</p>':action==='delete'?`<p>${esc(tr('dialog.deleteWarning'))}</p><p><strong>${esc(s.title)}</strong></p>${field('confirm_title',tr('field.confirmTitle'),'','required autocomplete="off"')}`:action==='rename'?field('title',tr('field.sessionTitle'),s.title,'required maxlength="200"'):`<p>${esc(s.title)}</p><p class="muted">${esc(action==='fork'?tr('dialog.forkHint'):action==='archive'?tr('dialog.archiveHint'):tr('dialog.restoreHint'))}</p>`,async values=>{await mutate('/console-api/session/'+encodeURIComponent(s.id),{action,...values,...(action==='delete'?{confirm_session_id:s.id}:{})});await loadSessions();await refresh();});};
$('new-session').onclick=()=>openAction(tr('dialog.newSession'),field('directory',tr('field.directory'),'','required list="workspace-options" placeholder="/path/to/project"')+field('title',tr('field.sessionTitle'),'','required maxlength="200"'),async v=>{await mutate('/console-api/sessions',v);await loadSessions();});
function profileRows(){return [...$('profile-list').querySelectorAll('.profile-card')];}
function addProfile(id='',p={}){const card=document.createElement('div');card.className='profile-card';card.innerHTML=`<div class="profile-card-top"><strong>${esc(p.label||id||tr('profile.new'))}</strong><button type="button" class="text-button remove-profile">${tr('action.remove')}</button></div><div class="form-grid">${field('id',tr('field.profileId'),id,'required pattern="[a-z][a-z0-9-]*"')}${field('label',tr('field.displayName'),p.label||id,'maxlength="100"')}${field('model',tr('field.providerModel'),p.model||'','required list="model-options" placeholder="provider/model"')}${field('variant',tr('field.variant'),p.variant||'','placeholder="'+esc(tr('field.variantPlaceholder'))+'"')}</div><label class="check-label"><input name="enabled" type="checkbox" ${p.enabled===false?'':'checked'}>${tr('field.enabled')}</label>`;card.querySelector('.remove-profile').onclick=()=>{card.remove();renderRouting();};card.querySelector('[name=id]').onchange=renderRouting;card.querySelector('[name=enabled]').onchange=renderRouting;$('profile-list').append(card);}
function readProfiles(){const result={};for(const card of profileRows()){const get=n=>card.querySelector(`[name=${n}]`).value.trim();const id=get('id');if(!/^[a-z][a-z0-9-]*$/.test(id))throw Error(tr('error.profileId'));if(result[id])throw Error(tr('error.profileDuplicate'));result[id]={model:get('model'),label:get('label')||id,enabled:card.querySelector('[name=enabled]').checked};if(get('variant'))result[id].variant=get('variant');}return result;}
function renderRouting(initial){let profiles;try{profiles=readProfiles();}catch{return;}for(const key of ['fast','background','deep']){const select=$('route-'+key),value=initial?.[key]||select.value;select.innerHTML=Object.entries(profiles).filter(([,p])=>p.enabled).map(([id,p])=>`<option value="${esc(id)}">${esc(p.label)} · ${esc(id)}</option>`).join('');if([...select.options].some(o=>o.value===value))select.value=value;}}
async function loadSettings(){const [settings,catalog]=await Promise.all([request('/console-api/settings'),request('/console-api/models')]);modelSettings=settings;$('auto-approve').checked=settings.auto_approve!==false;const cp=settings.cleanup||{};$('cleanup-enabled').checked=!!cp.enabled;$('cleanup-min').value=cp.min_free_gb??5;$('cleanup-target').value=cp.target_free_gb??10;$('cleanup-age').value=cp.min_age_days??30;$('cleanup-keep').value=cp.keep_recent??20;modelCatalog=Array.isArray(catalog)?catalog:(catalog.providers||[]);$('profile-list').innerHTML='';for(const [id,p] of Object.entries(settings.profiles||{}))addProfile(id,p);$('max-parallel').value=settings.max_parallel;$('max-kimi').value=settings.max_kimi_parallel;$('max-steps').value=settings.max_steps;$('kimi-reserve').value=settings.kimi_reserve_percent;renderRouting(settings.routing||{fast:'fast-code',background:'senior-code',deep:'deep-research'});$('model-options').innerHTML=modelCatalog.flatMap(p=>(Array.isArray(p.models)?p.models:Object.values(p.models||{})).map(m=>`<option value="${esc(p.id+'/'+m.id)}">${esc(m.name||m.id)}</option>`)).join('');$('provider-list').innerHTML=modelCatalog.map(p=>`<div class="provider-row"><strong>${esc(p.name||p.id)}</strong><span class="muted">${p.connected?tr('provider.connected'):tr('provider.disconnected')} · ${tr('provider.models',{n:Array.isArray(p.models)?p.models.length:Object.keys(p.models||{}).length})}</span><label class="provider-limit">${tr('provider.limit')}<input type="number" min="1" max="16" data-provider-limit="${esc(p.id)}" value="${esc(settings.provider_limits?.[p.id]??'')}" placeholder="${esc(tr('provider.inherit'))}"></label></div>`).join('')||'<p class="muted">'+tr('provider.none')+'</p>';}
$('add-profile').onclick=()=>addProfile();$('reload-settings').onclick=()=>loadSettings().catch(notice);
$('save-settings').onclick=async()=>{const b=$('save-settings');b.disabled=true;$('settings-message').textContent=tr('settings.applying');try{const body={revision:modelSettings?.revision||0,auto_approve:$('auto-approve').checked,cleanup:{enabled:$('cleanup-enabled').checked,min_free_gb:Number($('cleanup-min').value),target_free_gb:Number($('cleanup-target').value),min_age_days:Number($('cleanup-age').value),keep_recent:Number($('cleanup-keep').value),interval_seconds:3600},profiles:readProfiles(),max_parallel:Number($('max-parallel').value),max_kimi_parallel:Number($('max-kimi').value),max_steps:Number($('max-steps').value),kimi_reserve_percent:Number($('kimi-reserve').value),routing:Object.fromEntries(['fast','background','deep'].map(k=>[k,$('route-'+k).value])),provider_limits:Object.fromEntries([...document.querySelectorAll('[data-provider-limit]')].filter(x=>x.value!=='').map(x=>[x.dataset.providerLimit,Number(x.value)]))};const saved=await mutate('/console-api/settings',body);modelSettings=saved;$('settings-message').textContent=tr('settings.saved');await refresh();}catch(e){$('settings-message').textContent=e.message;}finally{b.disabled=false;}};
$('new-task').onclick=()=>{const options=Object.entries(data.profiles||{}).map(([id,p])=>`<option value="${esc(id)}">${esc(p.label)}</option>`).join('');openAction(tr('dialog.newTask'),field('title',tr('field.taskTitle'),'','required maxlength="200"')+field('directory',tr('field.directory'),'','required list="workspace-options" placeholder="/path/to/project"')+'<label>'+esc(tr('field.objective'))+'<textarea name="objective" required rows="4"></textarea></label>'+field('group_title',tr('field.groupTitle'),tr('field.manualTask'))+`<div class="form-grid"><label>${esc(tr('field.profile'))}<select name="profile"><option value="auto">${esc(tr('profile.auto'))}</option>${options}</select></label><label>${esc(tr('field.mode'))}<select name="mode"><option value="read">${esc(tr('field.readOnly'))}</option><option value="write">${esc(tr('field.write'))}</option></select></label><label>${esc(tr('field.workspace'))}<select name="workspace"><option value="auto">${esc(tr('field.auto'))}</option><option value="isolated">${esc(tr('field.isolated'))}</option></select></label><label>${esc(tr('field.urgency'))}<select name="urgency"><option value="background">${esc(tr('field.background'))}</option><option value="fast">${esc(tr('field.fast'))}</option></select></label></div><label>${esc(tr('field.acceptance'))}<textarea name="acceptance" rows="2"></textarea></label><label>${esc(tr('field.scopes'))}<textarea name="scopes" rows="2" placeholder="src/module.py"></textarea></label><label>${esc(tr('field.commands'))}<textarea name="commands" rows="2" placeholder="python3 -m unittest -v"></textarea></label>`,async v=>{const lines=s=>s.split('\n').map(x=>x.trim()).filter(Boolean);await mutate('/console-api/tasks',{...v,scopes:lines(v.scopes),commands:lines(v.commands),acceptance:lines(v.acceptance),group_id:'manual:'+v.directory});await refresh();});};
document.addEventListener('click',e=>{const b=e.target.closest('[data-cancel-task]');if(!b)return;openAction(tr('dialog.stopTask'),'<p>'+esc(tr('dialog.stopHint'))+'</p>',async()=>{await mutate('/console-api/task/'+b.dataset.cancelTask+'/cancel',{});await refresh();});});
setInterval(()=>{if(activeView==='sessions'&&!document.hidden&&!$('action-dialog').open)loadSessions().catch(notice);},10000);

async function loadWorkspaces(){const items=await request('/console-api/workspaces');$('workspace-options').innerHTML=items.map(w=>`<option value="${esc(w.directory)}">${esc(w.name)}</option>`).join('');}
$('add-workspace').onclick=()=>openAction(tr('dialog.addWorkspace'),field('name',tr('field.workspaceName'),'','required maxlength="100"')+field('directory',tr('field.directory'),'','required'),async v=>{await mutate('/console-api/workspaces',v);await loadWorkspaces();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-steer-task]');if(!b)return;const requestId=crypto.randomUUID();openAction(tr('dialog.steer'),'<label>'+esc(tr('field.steerText'))+'<textarea name="text" required rows="5" maxlength="24000"></textarea></label><p class="muted">'+esc(tr('dialog.steerHint'))+'</p>',async v=>{const result=await mutate('/console-api/task/'+b.dataset.steerTask+'/steer',{text:v.text,request_id:requestId});if(result.status!=='accepted')throw Error(tr('error.steerStatus',{status:result.status}));await refresh();});});

$('cleanup-preview').onclick=async()=>{try{const p=await request('/console-api/cleanup');$('cleanup-message').textContent=tr('cleanup.previewResult',{free:fixed1(p.free_bytes/2**30),count:p.candidate_count,size:fixed1(p.candidate_bytes/2**20)}); }catch(e){$('cleanup-message').textContent=e.message;}};
$('cleanup-run').onclick=()=>openAction(tr('dialog.cleanup'),'<p>'+esc(tr('dialog.cleanupHint'))+'</p>',async()=>{const r=await mutate('/console-api/cleanup',{apply:true});$('cleanup-message').textContent=r.skipped?tr('cleanup.skipped',{reason:r.skipped}):tr('cleanup.done',{removed:r.removed.length,errors:r.errors.length});});
document.addEventListener('i18n:change',()=>{applyViewLabels();if(activeView==='sessions')loadSessions().catch(notice);else if(activeView==='models')loadSettings().catch(notice);});
